<a href="https://colab.research.google.com/github/datadigger01/AppStatMat/blob/main/FlightDelay_NaiveBayes_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 항공기 지연데이터

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datadigger01/AppStatMat/main/Data/FlightDelays.csv"
df = pd.read_csv(url)
display(df.head())

,CRS_DEP_TIME,CARRIER,DEP_TIME,DEST,DISTANCE,FL_DATE,FL_NUM,ORIGIN,Weather,DAY_WEEK,DAY_OF_MONTH,TAIL_NUM,Flight Status
0,1455,OH,1455,JFK,184,01/01/2004,5935,BWI,0,4,1,N940CA,ontime
1,1640,DH,1640,JFK,213,01/01/2004,6155,DCA,0,4,1,N405FJ,ontime
2,1245,DH,1245,LGA,229,01/01/2004,7208,IAD,0,4,1,N695BR,ontime
3,1715,DH,1709,LGA,229,01/01/2004,7215,IAD,0,4,1,N662BR,ontime
4,1039,DH,1035,LGA,229,01/01/2004,7792,IAD,0,4,1,N698BR,ontime

In [ ]:
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2201 entries, 0 to 2200
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CRS_DEP_TIME   2201 non-null   int64
 1   CARRIER        2201 non-null   object
 2   DEP_TIME       2201 non-null   int64
 3   DEST           2201 non-null   object
 4   DISTANCE       2201 non-null   int64
 5   FL_DATE        2201 non-null   object
 6   FL_NUM         2201 non-null   int64
 7   ORIGIN         2201 non-null   object
 8   Weather        2201 non-null   int64
 9   DAY_WEEK       2201 non-null   int64
 10  DAY_OF_MONTH   2201 non-null   int64
 11  TAIL_NUM       2201 non-null   object
 12  Flight Status  2201 non-null   object
dtypes: int64(7), object(6)
memory usage: 223.7+ KB
None

,CRS_DEP_TIME,CARRIER,DEP_TIME,DEST,DISTANCE,FL_DATE,FL_NUM,ORIGIN,Weather,DAY_WEEK,DAY_OF_MONTH,TAIL_NUM,Flight Status
0,1455,OH,1455,JFK,184,01/01/2004,5935,BWI,0,4,1,N940CA,ontime
1,1640,DH,1640,JFK,213,01/01/2004,6155,DCA,0,4,1,N405FJ,ontime
2,1245,DH,1245,LGA,229,01/01/2004,7208,IAD,0,4,1,N695BR,ontime
3,1715,DH,1709,LGA,229,01/01/2004,7215,IAD,0,4,1,N662BR,ontime
4,1039,DH,1035,LGA,229,01/01/2004,7792,IAD,0,4,1,N698BR,ontime
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2196,645,RU,644,EWR,199,1/31/2004,2761,DCA,0,6,31,N15555,ontime
2197,1700,RU,1653,EWR,213,1/31/2004,2497,IAD,0,6,31,N16976,ontime
2198,1600,RU,1558,EWR,199,1/31/2004,2361,DCA,0,6,31,N14902,ontime
2199,1359,RU,1403,EWR,199,1/31/2004,2216,DCA,0,6,31,N16961,ontime
2200,1730,RU,1736,EWR,199,1/31/2004,2097,DCA,0,6,31,N13994,ontime

## 1. 컬럼명 타입 변환
- FL_DATE 컬럼은 date 타입으로 변환

In [ ]:
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'])

display(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2201 entries, 0 to 2200
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CRS_DEP_TIME   2201 non-null   int64
 1   CARRIER        2201 non-null   object
 2   DEP_TIME       2201 non-null   int64
 3   DEST           2201 non-null   object
 4   DISTANCE       2201 non-null   int64
 5   FL_DATE        2201 non-null   datetime64[ns]
 6   FL_NUM         2201 non-null   int64
 7   ORIGIN         2201 non-null   object
 8   Weather        2201 non-null   int64
 9   DAY_WEEK       2201 non-null   int64
 10  DAY_OF_MONTH   2201 non-null   int64
 11  TAIL_NUM       2201 non-null   object
 12  Flight Status  2201 non-null   object
dtypes: datetime64[ns](1), int64(7), object(5)
memory usage: 223.7+ KB

None

,CRS_DEP_TIME,CARRIER,DEP_TIME,DEST,DISTANCE,FL_DATE,FL_NUM,ORIGIN,Weather,DAY_WEEK,DAY_OF_MONTH,TAIL_NUM,Flight Status
0,1455,OH,1455,JFK,184,2004-01-01,5935,BWI,0,4,1,N940CA,ontime
1,1640,DH,1640,JFK,213,2004-01-01,6155,DCA,0,4,1,N405FJ,ontime
2,1245,DH,1245,LGA,229,2004-01-01,7208,IAD,0,4,1,N695BR,ontime
3,1715,DH,1709,LGA,229,2004-01-01,7215,IAD,0,4,1,N662BR,ontime
4,1039,DH,1035,LGA,229,2004-01-01,7792,IAD,0,4,1,N698BR,ontime
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2196,645,RU,644,EWR,199,2004-01-31,2761,DCA,0,6,31,N15555,ontime
2197,1700,RU,1653,EWR,213,2004-01-31,2497,IAD,0,6,31,N16976,ontime
2198,1600,RU,1558,EWR,199,2004-01-31,2361,DCA,0,6,31,N14902,ontime
2199,1359,RU,1403,EWR,199,2004-01-31,2216,DCA,0,6,31,N16961,ontime
2200,1730,RU,1736,EWR,199,2004-01-31,2097,DCA,0,6,31,N13994,ontime

## 2. Target 컬럼 생성
- 컬럼명 'Fight Status'의 값이 'ontime'이면 숫자 0 나머지(지연) 1으로 생성하여 delay_yn 컬럼명으로 새로 생성

In [ ]:
df['delay_yn'] = (df['Flight Status'] != 'ontime').astype(int)
display(df.head())

,CRS_DEP_TIME,CARRIER,DEP_TIME,DEST,DISTANCE,FL_DATE,FL_NUM,ORIGIN,Weather,DAY_WEEK,DAY_OF_MONTH,TAIL_NUM,Flight Status,delay_yn
0,1455,OH,1455,JFK,184,2004-01-01,5935,BWI,0,4,1,N940CA,ontime,0
1,1640,DH,1640,JFK,213,2004-01-01,6155,DCA,0,4,1,N405FJ,ontime,0
2,1245,DH,1245,LGA,229,2004-01-01,7208,IAD,0,4,1,N695BR,ontime,0
3,1715,DH,1709,LGA,229,2004-01-01,7215,IAD,0,4,1,N662BR,ontime,0
4,1039,DH,1035,LGA,229,2004-01-01,7792,IAD,0,4,1,N698BR,ontime,0

In [ ]:
df.columns

Index(['CRS_DEP_TIME', 'CARRIER', 'DEP_TIME', 'DEST', 'DISTANCE', 'FL_DATE',
       'FL_NUM', 'ORIGIN', 'Weather', 'DAY_WEEK', 'DAY_OF_MONTH', 'TAIL_NUM',
       'Flight Status', 'delay_yn'],
      dtype='object')

## 3. 결측값 확인 및 대체

In [ ]:
missing_values_count = df.isnull().sum()
display(missing_values_count)

CRS_DEP_TIME     0
CARRIER          0
DEP_TIME         0
DEST             0
DISTANCE         0
FL_DATE          0
FL_NUM           0
ORIGIN           0
Weather          0
DAY_WEEK         0
DAY_OF_MONTH     0
TAIL_NUM         0
Flight Status    0
delay_yn         0
dtype: int64

## 4.새로운 변수 파생
- CRS_DEP_TIME을 100으로 나누어 반올림(round) 처리 : 출발예정시간으로 오전 6:00 부터 10:00 사이를 18개의 그룹 등간격

- Fl_DATE 컬럼으로부터 월 추출

In [ ]:
df['CRS_DEP_TIME_G'] = round(df['CRS_DEP_TIME'] / 100).astype(int)

#df['DEP_MONTH'] = df['FL_DATE'].dt.month
#print(df.info())
display(df)

,CRS_DEP_TIME,CARRIER,DEP_TIME,DEST,DISTANCE,FL_DATE,FL_NUM,ORIGIN,Weather,DAY_WEEK,DAY_OF_MONTH,TAIL_NUM,Flight Status,delay_yn,CRS_DEP_TIME_G
0,1455,OH,1455,JFK,184,2004-01-01,5935,BWI,0,4,1,N940CA,ontime,0,15
1,1640,DH,1640,JFK,213,2004-01-01,6155,DCA,0,4,1,N405FJ,ontime,0,16
2,1245,DH,1245,LGA,229,2004-01-01,7208,IAD,0,4,1,N695BR,ontime,0,12
3,1715,DH,1709,LGA,229,2004-01-01,7215,IAD,0,4,1,N662BR,ontime,0,17
4,1039,DH,1035,LGA,229,2004-01-01,7792,IAD,0,4,1,N698BR,ontime,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2196,645,RU,644,EWR,199,2004-01-31,2761,DCA,0,6,31,N15555,ontime,0,6
2197,1700,RU,1653,EWR,213,2004-01-31,2497,IAD,0,6,31,N16976,ontime,0,17
2198,1600,RU,1558,EWR,199,2004-01-31,2361,DCA,0,6,31,N14902,ontime,0,16
2199,1359,RU,1403,EWR,199,2004-01-31,2216,DCA,0,6,31,N16961,ontime,0,14
2200,1730,RU,1736,EWR,199,2004-01-31,2097,DCA,0,6,31,N13994,ontime,0,17

In [ ]:
# 그룹별 발생빈도 확인
df['CRS_DEP_TIME_G'].value_counts()

CRS_DEP_TIME_G
15    292
17    241
16    178
8     164
12    142
21    137
7     133
13    132
6     126
14    123
19    119
9     108
10    100
18     85
11     68
20     53
Name: count, dtype: int64

In [ ]:
df.to_csv('FlightDelays_new.csv', index=False)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load data
#df = pd.read_csv("FlightDelays_new.csv")

# 2. Define features and target
feature_cols = [
    "CARRIER",
    "DEST",
    "DISTANCE",
    "ORIGIN",
    "Weather",
    "DAY_WEEK",
    "DAY_OF_MONTH",
    "CRS_DEP_TIME_G",
    "DEP_TIME",
]
X = df[feature_cols]
y = df["delay_yn"]

# 3. Train / test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 4. Preprocessing: one-hot for categoricals, pass-through for numerics
categorical_features = ["CARRIER", "DEST", "ORIGIN"]
numeric_features = [
    "DISTANCE",
    "Weather",
    "DAY_WEEK",
    "DAY_OF_MONTH",
    "CRS_DEP_TIME_G",
    "DEP_TIME",
]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numeric_features),
    ]
)

# 5. Naive Bayes model (GaussianNB)
nb_clf = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", GaussianNB())
])

# 6. Train
nb_clf.fit(X_train, y_train)

# 7. Evaluate
y_pred = nb_clf.predict(X_test)

print("Accuracy: {:.4f}".format(accuracy_score(y_test, y_pred)))
print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification report:")
print(classification_report(y_test, y_pred, digits=4))

# 8. Example: predicted delay probability for first 5 test samples
y_proba = nb_clf.predict_proba(X_test[:5])
print("\nPredicted probabilities (first 5 rows):")
print(y_proba)

Accuracy: 0.7732

Confusion matrix:
[[325  30]
 [ 70  16]]

Classification report:
              precision    recall  f1-score   support

           0     0.8228    0.9155    0.8667       355
           1     0.3478    0.1860    0.2424        86

    accuracy                         0.7732       441
   macro avg     0.5853    0.5508    0.5545       441
weighted avg     0.7302    0.7732    0.7449       441


Predicted probabilities (first 5 rows):
[[9.84989905e-01 1.50100947e-02]
 [9.99953850e-01 4.61501833e-05]
 [8.90358180e-01 1.09641820e-01]
 [9.99688872e-01 3.11127909e-04]
 [9.99793040e-01 2.06960041e-04]]